### ISSUE TITLE
Branch pete-java-11: Packaging with jpackage version 13-internal fails on Linux [+ fix]

### ISSUE THREAD

**Issue by skalteis** [petebankhead/qupath#24]
Hi Peter,

I just successfully built your Java 11 devel branch on Linux, however packaging using jpackage from OpenJDK 13 fails, jpackage just exits displaying its version information.

The troubling part is the assembly of the command line arguments to jpackage in the build script.

`// Strip off any SNAPSHOT part, which can cause trouble
    params << '--version' << qupathVersion.replace('-SNAPSHOT', '')
`

Replacing `--version` with `--app-version` fixes it & results in a working package.

Thank you & best regards

Simon

**Comment by petebankhead** [comment]
Thanks Simon, good to know!  Had it working on Windows & macOS, but with a different jpackage version - good to know what troubles will be in store (and the solution) when I return to look at packaging soon.

**Comment by petebankhead** [comment]
Can confirm this solution works for me, also on Windows (thanks again, could've taken a long time to track down the problem...) - https://github.com/petebankhead/qupath/commit/3454101cded143519c54e42787b7f395bb97d803

For what it's worth, two remaining sources of some difficulty with the switch to jpackage are:
* Can't set memory limits as was previously possible with JavaFX packager (haven't investigated alternatives)
* OpenSlide native libraries can't be loaded on Windows (easily)

Specifically, the first dll can be loaded but it fails to find the other dll's that it requires.  Adding the directory to the (user) path resolves this.  So too does moving the dll's to the same directory as the .exe (although it is getting rather crowded....).  However, I'm wondering if it's better to require the user to install/set up OpenSlide for all platforms explicitly, rather than attempting to include it by default - given that it can be somewhat problematic on Linux and Mac also.
