### ISSUE TITLE
Using CTRL to multiple select annotation object

### ISSUE THREAD

**Issue by JoelRV** [petebankhead/qupath#25]
Hi there,

After having successfully compiled the latest build 0.1.3-SNAPSHOT using gradle on Ubuntu 16.04 (Linux  -  4.13.0-45-generic, java 8), your awesome software runs mostly stable.

However I noticed an unfortunate bug where when I try using CTRL+CLICK to select multiple annotation objects in the Annotations tab, not only does it not work but it completely freezes the application and my machine. Ressource-wise it starts hogging 100% of one cpu core and the whole ubuntu interface stops reacting, forcing me to kill the QuPath instance.

If you need any more information to pinpoint the root cause of this strange behavior, feel free to ask for any extra information you might need.

Best regards,
JRV

**Comment by petebankhead** [comment]
Good!  Partly.  I will look out for this, but synchronizing selected objects with the hierarchy view has proven nothing but trouble whenever there are a large number of objects (e.g. many cells), and especially if these are split across relatively view annotations.  Expanding the nodes in the tree can result in things grinding to a halt.  It doesn't matter where the objects are selected, the hierarchy tree will try to synchronize to the current selection and this is the bit that can go bad.

Could this describe your situation also?

In my current codebase (not sure if it's in the v0.1.3 branch - but worth a look) there is an option in the preferences called 'Hierarchy detection display' where you can stop detections being shown in the tree view.  If you do this, it should make the problem go away... assuming I've guessed correctly that the cause is synchronizing selections when there are too many objects in the tree.

**Comment by JoelRV** [comment]
Hi and thanks for the fast feedback.

Indeed after finding the 'Hierarchy detection display' option and setting it to "None", it seems to stop the bug from occurring. As you guessed, i was doing some test runs on a high resolution tissue slide with ca. 150k tiles in and Area. After adding a sub-ROI and trying to select both in the Annotation tab, the aforementioned bug occurred.

Might I ask what feature the  'Hierarchy detection display' governs? I.e. what noticeable consequence change this option will produce?

**Comment by petebankhead** [comment]
Glad to hear it!  The option really just changes whether or not your 150k tiles are included in the tree display under the 'Hierarchy' tab.  If they are, you can potentially select the object from the tree (although good luck finding the one you're after...).

The idea was that it meant every object was accessible in some way in a list/tree form from that tabbed pane on the left, rather than only by selecting it in the image.  For the TMAs I worked with most of the time, it was actually ok - even with a few hundred thousands cells in the image, each individual core generally had only a few thousand cells inside it and the performance was fine.  But when working with large tissue sections, where a single annotation might have hundreds of thousands of cells or tiles _directly below it_ (and not dispersed among other 'sub-'annotations), trying to include all of them in the tree view seems to do far more harm than good.

**Comment by JoelRV** [comment]
Noted!
Thabks again. Feel free to close the issue ag your own discretion.
