### ISSUE TITLE
Sorting project images

### ISSUE THREAD

**Issue by Tkilvaer** [petebankhead/qupath#27]
Perhaps this is more of a feature request. However. Currently QuPath sorts images in a project as character. If the images are numbered insted they show up as 1, 11, 12, 13, 14 etc. It would be nice to be able to parse image names as numbers if they indeed are numbers.

I do not know how much effort this is. It is a convenience feature and should not be proritized over other more pressing issues.

**Comment by petebankhead** [comment]
I turned off the automatic sorted in my code, as it was annoying me for similar reasons. It would then depend on the order in which the images are added (potentially this could be edited later).

I think parsing would be hard as there could be multiple numbers in various places (slide numbers, dates...)... but hopefully the lack of auto-sorting will already help quite a bit.

Projects are currently undergoing a major revision, because the need for every image name to be unique was proving troublesome as well.  More news in the next week or two...

**Comment by petebankhead** [comment]
Sorry there was no news 'in a week or two' after all.

Much has changed in v0.2.0. Sorting in a project is not yet a thing, but the search field at the bottom can help, as can (still to be properly documented) metadata files for project entries.

I've just tested with numbered images, and if I drag them onto QuPath for import it will use the order in which the files were selected... which gives a workaround of sorts.

I'll close this because and my fork isn't really the best place for discussing this; feel free to revive at http://forum.image.sc/tags/qupath if needed.
